trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'shushankacr2026'
  imageRepository: 'portfolio'

steps:
  - script: |
      docker build -t $(imageRepository):$(Build.BuildId) .
    displayName: 'Build Docker Image'

  - task: AzureCLI@2
    displayName: 'Push Image to ACR'
    inputs:
      azureSubscription: 'Azure-ServiceConnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr login --name $(acrName)

        docker tag $(imageRepository):$(Build.BuildId) \
          $(acrName).azurecr.io/$(imageRepository):$(Build.BuildId)

        docker push \
          $(acrName).azurecr.io/$(imageRepository):$(Build.BuildId)

  - task: AzureCLI@2
    displayName: 'Deploy to App Service'
    inputs:
      azureSubscription: 'Azure-ServiceConnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp config container set \
          --name shushank-portfolio-2026 \
          --resource-group portfolio-rg \
          --container-image-name $(acrName).azurecr.io/$(imageRepository):$(Build.BuildId)
